name: Dados abertos da RFB

on:
  push:
  workflow_dispatch:    
  schedule:
    - cron: '0 0 25 * *'  

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./download.sh
      - uses: actions/upload-artifact@v4
        with:
          path: tmp/*.zip
